# Generated by Django 5.1 on 2024-08-19 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_users_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('date', models.DateTimeField(auto_now=True)),
                ('urgency_level', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Ultra', 'Ultra')], max_length=6)),
                ('score', models.IntegerField()),
                ('action', models.CharField(choices=[('Update Medical Records', 'Update Medical Records'), ('Order Diagnostic Tests', 'Order Diagnostic Tests'), ('Refer to Specialist', 'Refer to Specialist'), ('Discharge Patient', 'Discharge Patient'), ('Provide Health Education', 'Provide Health Education'), ('Perform a Procedure', 'Perform a Procedure')], max_length=255)),
            ],
        ),
    ]
