# Generated by Django 5.1 on 2024-08-22 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_patient'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
