# Generated by Django 5.1 on 2024-08-23 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_gender'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gender',
        ),
    ]
