# Generated by Django 5.1 on 2024-08-23 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_delete_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('is_manager', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
