# Generated by Django 5.1 on 2024-08-24 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_delete_manager_users_note_users_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='note',
        ),
        migrations.RemoveField(
            model_name='users',
            name='status',
        ),
        migrations.AddField(
            model_name='patient',
            name='note',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='patient',
            name='status',
            field=models.CharField(default='', max_length=255),
        ),
    ]
