# Generated by Django 5.1 on 2024-08-26 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_remove_users_note_remove_users_status_patient_note_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='users',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='users',
            name='user_permissions',
        ),
    ]
