# Generated by Django 5.1 on 2024-08-26 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_remove_users_groups_remove_users_is_superuser_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender_female_score', models.IntegerField(default=20)),
                ('gender_male_score', models.IntegerField(default=15)),
                ('age_above_65_or_below_5_score', models.IntegerField(default=30)),
                ('age_between_5_and_10_or_55_and_65_score', models.IntegerField(default=20)),
                ('age_others_score', models.IntegerField(default=15)),
                ('urgency_ultra_score', models.IntegerField(default=40)),
                ('urgency_high_score', models.IntegerField(default=30)),
                ('urgency_medium_score', models.IntegerField(default=20)),
                ('urgency_low_score', models.IntegerField(default=10)),
                ('waiting_time_less_than_10_days_score', models.IntegerField(default=0)),
                ('waiting_time_11_to_30_days_score', models.IntegerField(default=5)),
                ('waiting_time_31_to_60_days_score', models.IntegerField(default=8)),
                ('waiting_time_above_60_days_score', models.IntegerField(default=10)),
            ],
        ),
    ]
