# Generated by Django 5.1 on 2024-08-27 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_alter_addlog_user_alter_deletelog_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.users'),
        ),
        migrations.AlterField(
            model_name='deletelog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.users'),
        ),
        migrations.AlterField(
            model_name='editlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.users'),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.users'),
        ),
    ]
